### ISSUE TITLE
Add a mini-voice icon for voice channels

### ISSUE THREAD

**Issue by Freeplayg** [v-briese/channel-icons#3]
**Is your feature request related to a problem? Please describe.**
Sometimes it's hard to tell what's a voice channel and what isn't
![2021-05-17_19-42](https://user-images.githubusercontent.com/40742947/118569531-1e5ef500-b748-11eb-81e0-8fafc6425e6d.png)

**Describe the solution you'd like**
A little voice icon at the top left would help with that!

**Describe alternatives you've considered**
no

**Comment by v-briese** [comment]
Similar to issue #4, merging issues.
