### ISSUE TITLE
Overlay important channel info, such as whether the channel is locked or a voice channel.

### ISSUE THREAD

**Issue by gdude2002** [v-briese/channel-icons#4]
> Edit from @v-briese: overlay smaller icons to show information about a channel, such as if it's locked or a voice channel.

**Is your feature request related to a problem? Please describe.**
Really love this idea, but (in Powercord at least) icons for channels that would usually have a lock icon (to show that `@everyone` can't view the channel) are replaced with icons that don't have anything that shows this.

**Describe the solution you'd like**
It'd be great to get icon variants that make this (pretty important) information visible again - I guess you could overlay a padlock like the client already does, but there may be a better option.

**Describe alternatives you've considered**
I had a thought about drawing a diagonal line to "cross out" the icon instead, but I feel like that'd be a lot messier than a small additional icon overlaid.

**Additional context**
Unfortunately, I'm not super familiar with how Discord's styling and DOM layout works - if this isn't possible natively then maybe there's a plugin that adds some extra classes to use as selectors?

**Comment by v-briese** [comment]
Sounds plausible. Either I could manually make locked variants of every icon (which doesn't sound very fun lol) or I could dynamically apply a mask with a locked icon over other icons (which I'm not entirely sure how to do).

**Comment by gdude2002** [comment]
I guess you could probably do it using pseudo-elements, eg `:before` and `:after`, but my CSS-fu needs some work too haha

**Comment by Freeplayg** [comment]
You could use ::before to add the other icon, then add a stroke with the same color as the background on the icon for separation

**Comment by v-briese** [comment]
Resolved in [v2.0.1](https://github.com/v-briese/channel-icons/blob/main/CHANGELOG.md#201---2021-06-11), forgot to close this issue lol

**Comment by gdude2002** [comment]
Looks good, that's a :+1: from me! The only criticism I have is that the lock is usually at the top of the icon rather than below it, but that's really going to be specific to whatever other themes you're using. Maybe it'd be possible to use [CSS Variables](https://css-tricks.com/everything-need-know-css-variables/) for the positioning?

**Comment by v-briese** [comment]
> The only criticism I have is that the lock is usually at the top of the icon rather than below it, but that's really going to be specific to whatever other themes you're using.

Yeah, I had to have it in the *bottom* right because Discord doesn't actually have any masks with a hole in the *top* right. The only way for me to that would be to make a custom locked variant for *every* icon, which I'm honestly way too lazy to do haha.

**Comment by gdude2002** [comment]
Oh, that's interesting, I thought you'd have overlaid it with CSS. Alright, makes sense, no worries!
